[[redirects]]
  from = "/"
  to = "/en"
  status = 301
  force = true

[[redirects]]
  from = "/*"
  to = "/.next/server/pages/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200